all:
	# optimize -O0 ~ -O3
	# 0 -> compile's time is the fastest
	# 3 -> compile's time is the slowest
	# OBJECT:
		# gcc -Wall -O3 -c optimize.c
	#gcc -Wall -O3 optimize.c -o a.out
	#gcc -Wall -O3 optimize.c 
	gcc -Wall -g optimize.c
	#./a.out

 # debugging option is default into -O2
 # option : -g
 
clean:
	@rm *.out
	@rm *.*~
	@rm *~
